//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessModule.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Achievement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Achievement()
        {
            this.UserAchievements = new HashSet<UserAchievement>();
        }
    
        public int AchievementId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> RequiredWins { get; set; }
        public Nullable<int> RequiredGames { get; set; }
        public Nullable<int> RequiredWinStreak { get; set; }
        public Nullable<int> RequiredMaxMoves { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAchievement> UserAchievements { get; set; }
    }
}
