//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessModule.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameHistory
    {
        public int GameId { get; set; }
        public int UserId { get; set; }
        public string Result { get; set; }
        public System.DateTime GameDate { get; set; }
        public string OpponentType { get; set; }
        public Nullable<int> BotDifficulty { get; set; }
        public string GameDifficulty { get; set; }
        public int MovesCount { get; set; }
        public int DurationSeconds { get; set; }
        public string FinishReason { get; set; }
        public string Winner { get; set; }
    
        public virtual User User { get; set; }
    }
}
