//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessModule.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavedGame
    {
        public int SaveId { get; set; }
        public int UserId { get; set; }
        public string SaveName { get; set; }
        public string Mode { get; set; }
        public int BotDifficulty { get; set; }
        public string GameDifficulty { get; set; }
        public string Fen { get; set; }
        public int WhiteTimeSeconds { get; set; }
        public int BlackTimeSeconds { get; set; }
        public int MoveCount { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string MoveLog { get; set; }
    
        public virtual User User { get; set; }
    }
}
