//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessModule.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReward
    {
        public int UserRewardId { get; set; }
        public int UserId { get; set; }
        public int RewardId { get; set; }
        public bool IsSelected { get; set; }
    
        public virtual Reward Reward { get; set; }
        public virtual User User { get; set; }
    }
}
