//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessModule.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSetting
    {
        public int UserSettingsId { get; set; }
        public int UserId { get; set; }
        public bool MusicEnabled { get; set; }
        public bool EffectsEnabled { get; set; }
        public bool ShowCoordinates { get; set; }
    
        public virtual User User { get; set; }
    }
}
